---
title: Cold Standby throws "DataStoreException Record does not exist"
description: Description
solution: Experience Manager
product: Experience Manager
applies-to: Experience Manager
keywords: KCS,AEM,coldstandby,DataStoreException
resolution: Resolution
internal-notes: https://issues.apache.org/jira/browse/OAK-8202,https://jira.corp.adobe.com/browse/GRANITE-11668
bug: false
article-created-by: Vincent Frey
article-created-date: 5/12/2022 3:39:59 PM
article-published-by: Vincent Frey
article-published-date: 5/12/2022 3:40:16 PM
version-number: 2
article-number: KA-15610
dynamics-url: https://adobe-ent.crm.dynamics.com/main.aspx?forceUCI=1&pagetype=entityrecord&etn=knowledgearticle&id=8e6000c7-09d2-ec11-a7b5-0022480a8683
exl-id: d37d0338-be4f-4660-a4b2-cd1179717e07
---
# Cold Standby throws "DataStoreException Record does not exist"

## Description


<b>Issue:</b>
 Cold standby with dedicated file Datastore throws warning on missing blobid like the one at 1.

<b>Details:</b>
 This is just a warning, not an error. It comes from the fact that the datastore has no way to verify if a binary exists locally, except by trying to load blob id.
 If the id gets loaded, the logs don't show this warning. However, if it's not found, the standby knows that it has to sync it, so we see the warning 1 in the logs.


 1: *\*WARN\* standby-run-1 org.apache.jackrabbit.oak.plugins.blob.datastore.DataStoreBlobStore Error occurred while loading bytes from steam while fetching for id f68a92b34779bbd194184251ec916370f3ebd301d6e32a8980aad070d57a1845#25522
<br>java.util.concurrent.ExecutionException: java.io.IOException: org.apache.jackrabbit.core.data.DataStoreException: Record f68a92b34779bbd194184251ec916370f3ebd301d6e32a8980aad070d57a1845 does not exist
<br>    at org.apache.jackrabbit.oak.cache.CacheLIRS$Segment.load(CacheLIRS.java:1017) org.apache.jackrabbit.oak-core-spi:1.10.3
<br>...
<br>Caused by: org.apache.jackrabbit.core.data.DataStoreException: Record cabdc49c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20 does not exist
<br>    at org.apache.jackrabbit.core.data.AbstractDataStore.getRecord(AbstractDataStore.java:59)*


## Resolution


This is working as designed and doesn't indicate a problem with the File DataStore.

<b>To confirm:</b>

- Sample blob id showing as missing in the logs: "cabdc49c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20"
- For this blob id, the filesystem address should be: "ca/bd/c4/9c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20"
- Search the filesystem on standy instance and check if the named file is present in the datastore.
- Within /repository/datastore, use list (ls -ald) command: "ls -ald ca/bd/c4/9c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20"
- You should be able to see the file and confirm that the blob id is actually not missing
